# Generated by Django 3.0.3 on 2020-02-18 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='contents',
            new_name='completed',
        ),
    ]
