# Generated by Django 3.0.3 on 2020-02-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0002_auto_20200218_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='notes',
            field=models.CharField(default='', max_length=100),
        ),
    ]
